FROM node
RUN apt update
RUN apt install npm -y
RUN npm install node-mysql -g
RUN npm install -g n
COPY admin/. /admin
RUN n stable
RUN yarn add create-react-app
WORKDIR /admin
RUN npm install mysql node-mysql --save 
RUN yarn install
RUN yarn build
EXPOSE 80
CMD ["yarn", "run", "start"]


FROM node
RUN apt update && \
    apt install npm -y
RUN npm install node-mysql -g && \
    npm install -g n && \
    n stable && \
    yarn add create-react-app
COPY admin/. /admin
WORKDIR /admin
RUN npm install mysql node-mysql --save
RUN yarn install
RUN yarn build
EXPOSE 80
CMD ["yarn", "run", "start"]